/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#faf8ff',
        'surface-dim': '#d6d9ef',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f2ff',
        'surface-container': '#ebedff',
        'surface-container-high': '#e4e7fe',
        'surface-container-highest': '#dee1f8',
        'on-surface': '#171b2b',
        'on-surface-variant': '#45464e',
        'inverse-surface': '#2c3041',
        'inverse-on-surface': '#eff0ff',
        'outline': '#76767f',
        'outline-variant': '#c6c5cf',
        'surface-tint': '#545d82',
        'primary': '#081234',
        'on-primary': '#ffffff',
        'primary-container': '#1e2749',
        'on-primary-container': '#868eb6',
        'inverse-primary': '#bcc5ef',
        'secondary': '#ae3026',
        'on-secondary': '#ffffff',
        'secondary-container': '#fc6959',
        'on-secondary-container': '#690003',
        'tertiary': '#00190e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00301e',
        'on-tertiary-container': '#00a472',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#bcc5ef',
        'on-primary-fixed': '#10193b',
        'on-primary-fixed-variant': '#3c4569',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#ffb4aa',
        'on-secondary-fixed': '#410001',
        'on-secondary-fixed-variant': '#8c1712',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#faf8ff',
        'on-background': '#171b2b',
        'surface-variant': '#dee1f8'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '2.5rem',
        'space-4xl': '3.5rem',
        'screen-edge-padding': '1.25rem',
        'card-inner-padding': '1.25rem',
        'touch-target-min': '3rem'
      },
      fontFamily: {
        'sans': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'code-license-plate': ['"Plus Jakarta Sans"', 'sans-serif']
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['15px', { lineHeight: '22px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
        'code-license-plate': ['20px', { lineHeight: '26px', letterSpacing: '0.08em', fontWeight: '800' }]
      }
    },
  },
  plugins: [],
}
